#!/bin/sh

sudo cp locale.conf /etc
sudo cp locale.gen /etc
sudo locale-gen

sudo cp mirrorlist /etc/pacman.d

sudo cp mkinitcpio.conf /etc

sudo cp suspend@.service /etc/systemd/system
sudo systemctl enable suspend@segfault

sudo mkdir -p /etc/pacman.d/hooks
sudo cp pkglist.hook /etc/pacman.d/hooks

sudo cp vconsole.conf /etc

